# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7faa348ccddb4bcd5c8d93b34724135cb8a0d7566deaff447b39a8463703ff2c3e6ff82b4c3631429054eaf9ee9a17ae9665c8bd5356ed13c54dc229fd00abd4

test:
  secret_key_base: 65f9061e9bc91a3cfb09a7789b04ec4c37fa34fac7cef73f10560b5f632c0f8066feed6a234aa2c6ec73a69ccfc003942a05fe38e4cf2a3366cd2a7781f816e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
